version: '3.4'

name: aspnet-identity
services:
  identitydb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  aspnetidentity:
    image: ${DOCKER_REGISTRY-}aspnetidentity
    build:
      context: .
      dockerfile: src/AspnetIdentity/Dockerfile
